# Generated by Django 2.1.5 on 2019-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190324_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='content',
        ),
        migrations.AddField(
            model_name='dataitem',
            name='isin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='lastprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='sinceclose',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='sinceopen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
